(function(ImagePair,EventDispatcher,$){ImagePair.Card=function(image,id,alt){var self=this;EventDispatcher.call(self);var path=H5P.getPath(image.path,id);alt=alt||'Missing description';self.isPaired=false;var width,height;if(image.width!==undefined&&image.height!==undefined){if(image.width>image.height){width='100%';height='auto';}else{height='100%';width='auto';}}else{width=height='100%';}
self.getImage=function(){return self.$card.find('img').clone();};self.setCorrect=function(){self.$pairingMark.addClass('correct-mark');self.$front.addClass('pair-item-correct');self.$rear.addClass('pair-item-correct');};self.setIncorrect=function(){self.$pairingMark.addClass('incorrect-mark');self.$front.addClass('pair-item-incorrect');self.$rear.addClass('pair-item-incorrect');};self.setSolved=function(){self.$pairingMark.addClass('solved-mark');self.$front.addClass('pair-item-solved');self.$rear.addClass('pair-item-solved');};self.setSelected=function(){self.isSelected=true;self.$card.addClass('h5p-image-pair-item-selected');};self.removeSelected=function(){self.isSelected=false;self.$card.removeClass('h5p-image-pair-item-selected');};self.makeTabbable=function(){if(self.$card){self.$card.attr('tabindex','0');}};self.makeUntabbable=function(){if(self.$card){self.$card.attr('tabindex','-1');}};self.setFocus=function(){self.makeTabbable();self.$card.focus();}
self.transform=function(){self.$card.removeClass('h5p-image-pair-item-hover').removeClass('droppable').droppable("option","disabled",true);};self.disable=function(){self.isPaired=true;self.$card.removeClass('h5p-image-pair-item-selected').addClass('h5p-image-pair-item-disabled');};self.pair=function(pair){self.srcImage=(self.srcImage)?self.srcImage:self.getImage();self.$top=self.$card;self.$top.html('').toggleClass('h5p-image-pair-images-paired',true);self.$pairingMark=$('<span class="pairing-mark"></span>').appendTo(self.$top);self.$front=$('<div class="card-paired front"><div class="h5p-image-pair-overlay"></div></div>').append(pair.getImage()).appendTo(self.$top);self.$rear=$('<div class="card-paired"><div class="h5p-image-pair-overlay"></div></div>').append(self.srcImage).appendTo(self.$top);self.$card.replaceWith(self.$top);self.$top.children('.card-paired').on('click',function(){pair.$card.removeClass('h5p-image-pair-item-disabled');self.detach();});self.$top.children('.card-paired').hover(function(){$(this).addClass('h5p-image-pair-item-hover');$(this).siblings('div').addClass('h5p-image-pair-item-hover');},function(){$(this).removeClass('h5p-image-pair-item-hover');$(this).siblings('div').removeClass('h5p-image-pair-item-hover');});self.isPaired=true;};self.detach=function(){self.isPaired=false;self.$card.removeClass('h5p-image-pair-images-paired').empty();$('<div class="image-container"></div>').append(self.srcImage).appendTo(self.$card);self.$card.removeClass('h5p-image-pair-item-selected').addClass('droppable').removeClass('h5p-image-pair-item-hover').droppable("option","disabled",false);self.trigger('unpair');};self.appendTo=function($container){self.$card=$('<li class="h5p-image-pair-item">'+
'<div class="image-container">'+
'<img src="'+path+'" alt="'+alt+'" style="width:'+
width+';height:'+height+'"/>'+
'<div class="h5p-image-pair-overlay"></div>'+
'</div>'+
'</li>').appendTo($container);self.$card.on('keydown',function(event){switch(event.which){case 13:self.trigger('makeSelection');event.preventDefault();return;case 32:self.trigger('shiftContainer');event.preventDefault();return;case 39:case 40:if(self.isPaired){self.trigger('nextPair');}else{self.trigger('next');}
return;case 37:case 38:if(self.isPaired){self.trigger('prevPair');}else{self.trigger('prev');}
return;case 35:if(self.isPaired){self.trigger('lastPair');}else{self.trigger('last');}
return;case 36:if(self.isPaired){self.trigger('firstPair');}else{self.trigger('first');}
return;}});self.$card.click(function(){self.trigger('selected');}).end();self.$card.hover(function(){$(this).addClass('h5p-image-pair-item-hover');},function(){$(this).removeClass('h5p-image-pair-item-hover');});};};ImagePair.Card.prototype=Object.create(EventDispatcher.prototype);ImagePair.Card.prototype.constructor=ImagePair.Card;ImagePair.Card.isValid=function(params){return(params!==undefined&&params.image!==undefined&&params.image.path!==undefined);};ImagePair.Card.hasTwoImages=function(params){return(params!==undefined&&params.match!==undefined&&params.match.path!==undefined);};})(H5P.ImagePair,H5P.EventDispatcher,H5P.jQuery);